@echo off
start cmd

rem start cmd /k "python parliament.py -p 1"
rem start cmd /k "python parliament.py -p 2"
rem start cmd /k "python parliament.py -p 3"
rem start cmd /k "python parliament.py -p 4"
rem start cmd /k "python parliament.py -p 5"
rem start cmd /k "python parliament.py -p 6"
rem start cmd /k "python parliament.py -p 7"
rem start cmd /k "python parliament.py -p 8"
rem start cmd /k "python parliament.py -p 9"
rem start cmd /k "python parliament.py -p 10"
rem start cmd /k "python parliament.py -p 11"
rem start cmd /k "python parliament.py -p 12"
rem start cmd /k "python parliament.py -p 13"
rem start cmd /k "python parliament.py -p 14"

start cmd /k "python parliament_from_txt.py -i id.txt -s 0 -e 3750"
start cmd /k "python parliament_from_txt.py -i id.txt -s 3750 -e 7500"
start cmd /k "python parliament_from_txt.py -i id.txt -s 7500 -e 11250"
start cmd /k "python parliament_from_txt.py -i id.txt -s 11250 -e 15000"
start cmd /k "python parliament_from_txt.py -i id.txt -s 15000 -e 18750"
start cmd /k "python parliament_from_txt.py -i id.txt -s 18750 -e 22500"
start cmd /k "python parliament_from_txt.py -i id.txt -s 22500 -e 26250"
start cmd /k "python parliament_from_txt.py -i id.txt -s 26250"